### ISSUE TITLE
这个gem好像不包含tree这种图，定制下载tree引入到视图中会覆盖gem本身的js

### ISSUE THREAD

**Issue by renji001** [echohn/echarts-rails#6]
这个应该怎么处理呢？不用gem 在官网定制一个包含tree的？

**Comment by echohn** [comment]
这个 gem 我已经不再维护了。
主要是 rails 5 集成 webpacker 以后，echarts 用 npm 或 yarn 构建更加方便。这种封装其实没多大意义了。

**Comment by echohn** [comment]
tree 是 echarts 3.8 版本新增的功能，以如果你需要，可以 fork 这个项目，将定制后的内容替换 `vendor/assets/javascripts/` 目录下的文件
